[Settings]
ID = "8a0f0c25-2a82-4bfb-988b-65e34a3fec6d"

[build]
  # This is the directory to change to before starting a build.
  base    = "/"
  # NOTE: This is where we will look for package.json/.nvmrc/etc, not root.
  # This is the directory that you are publishing from (relative to root of your repo)
  publish = "/site/"
  # This will be your default build command
  command = "bundle exec jekyll build"
