backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
  
media_folder: "images"

collections:
    - name: "Gallerij"
      label: "Gallerij"
      delete: false # Prevent users from deleting documents in this collection
      editor:
          preview: false
      files:
          - name: "Home"
            label: "Home Gallerij"
            file: "index.html"
            description: "Gallerij voor de home pagina"
            fields:
                - label: "Gallerij"
                  name: "gallery"
                  widget: "list"
                  field:
                      - label: "Image", 
						name: "image", 
						widget: "image"
